### ISSUE TITLE
Error trying to implement an NDB.KeyProperty

### ISSUE THREAD

**Issue by loughnane** [kamalgill/flask-appengine-template#50]
Right out of the box I have attempted to add an ndb.KeyProperty to models.py, and end up with an error saying that `KeyProperty has no attribute _reference_class`. I've traced this down to line 329 in `/src/lib/wtforms/ext/appengine/ndb.py`:

```
kwargs['reference_class'] = prop._reference_class
```

 It appears to be looking for 'reference_class' which is an old `db.model` idiom. The analog for ndb is `kind`, but swapping out line 329 with an instruction to look for the `kind` attribute just results in a deeper set of issues.

```
kwargs['reference_class'] = prop._kind
```

**Comment by kamalgill** [comment]
Closing, as workaround is reported to work.
