### ISSUE TITLE
Can gae_mini_profiler be installed via pip?

### ISSUE THREAD

**Issue by houmie** [kamalgill/flask-appengine-template#73]
I generally don't put the libs into my git repository and use `make setup` to download them instead.

I was wondering if I could delete lib/gae_mini_profiler and install it via pip?

`pip install gae_mini_profiler`

But I can't find any way to achieve this.  Please advice if you know a way.

Many Thanks,
Houman

**Comment by kamalgill** [comment]
Hi Houman,

You could try `pip install gae_mini_profiler -t lib`, but you may need to update to the latest pip version since older releases has had issues with the -t flag, which is fairly new to pip.

**Comment by houmie** [comment]
Hi Kamal,

I wished that was possible. I get this error message:
```
(news-env)Houman-MBP:requests houman$ pip install gae_mini_profiler
Downloading/unpacking gae-mini-profiler
  Could not find any downloads that satisfy the requirement gae-mini-profiler
Cleaning up...
No distributions at all found for gae-mini-profiler
Storing debug log for failure in /Users/houman/.pip/pip.log
```

**Comment by flamusdiu** [comment]
It's not pip installable. You can find more info from https://github.com/Khan/gae_mini_profiler/issues/74

You can try: pip install -e https://github.com/bogdanvarlamov/gae_mini_profiler.git@pip_support#egg=gae_mini_profiler 

It's the fork someone added the pip requirements too. Try at your own risk.
