### ISSUE TITLE
apptests.py fails 3 unit tests on fresh install

### ISSUE THREAD

**Issue by houmie** [kamalgill/flask-appengine-template#74]
```
test_404 (tests.DemoTestCase) ... ok
test_admin_login (tests.DemoTestCase) ... FAIL
test_displays_no_data (tests.DemoTestCase) ... FAIL
test_home_redirects (tests.DemoTestCase) ... ok
test_inserts_data (tests.DemoTestCase) ... FAIL
test_says_hello (tests.DemoTestCase) ... ok
```

Do I have to activate admin_login first somehow?

Many Thanks,
Houman

**Comment by pavelkraleu** [comment]
I fixed them [here](https://github.com/kamalgill/flask-appengine-template/pull/77)

**Comment by pavelkraleu** [comment]
Pull request has been merged, this issue can be closed @kamalgill

**Comment by kamalgill** [comment]
Fixed in https://github.com/kamalgill/flask-appengine-template/pull/77 , thanks @pavelkraleu!
