### ISSUE TITLE
Only for App Engine Standard / Python 2.7

### ISSUE THREAD

**Issue by adelespinasse** [kamalgill/flask-appengine-template#82]
I think this repo is intended only for App Engine standard environment, is that correct? I think the README.md should probably make that clear, since the official Flask docs link here to show how to run a Flask server on App Engine. (Possibly the Flask docs should be updated too.)

The [App Engine Flexible Environment quickstart](https://cloud.google.com/appengine/docs/flexible/python/quickstart) actually uses Flask in its sample code (with Python 3 and gunicorn), which is extremely simple and works great.

**Comment by kamalgill** [comment]
Good point... will note that and provide a link to the official quickstart and sample repo.

**Comment by kamalgill** [comment]
Readme updated... thank you for opening this @adelespinasse !
